#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -f constant/polyMesh/boundary
rm -f constant/polyMesh/sets/*_old
rm -rf constant/panelRegion/polyMesh
rm -rf constant/woodRegion/polyMesh
rm -rf constant/filmRegion/polyMesh
rm -rf patch* 
rm -f log.*
rm -f outFlameHeight*
rm -rf VTK
rm -rf HRR
rm -rf fieldMimMax
rm -rf zones
rm -rf 0/ccx  0/ccy  0/ccz  0/*Level
rm -rf 0/panelRegion/cellToRegion
rm -rf 0/polyMesh
# -----------------------------------------------------------------------------
